First-Capstone
Gmanlove/FIRST-CAPSTONE-PROJECT pull request #1
Opened 2023-02-09 18:06 UTC by Gmanlove

### **I did this capstone project by:**

- [ ] Creating a new repository for the project
- [ ] Creating a new branch (capstone1) for the project
- [ ] Checking out the Cindy shin template for the project and download some images that best fit the project
- [ ] Creating a Javascript file to design my hamburger bar and make the featured speaker section dynamic
- [ ] Ensuring no linter error
- [ ] Recording a video presenting the features of the project I built. which can be accessed by the link below.
(LOOM VIDEO) https://www.loom.com/share/bf2eb1a08afb4a9fbafd9b1f0612325c

2023-02-09 20:53 UTC, christianbiring1 requested changes
Hi @Gmanlove , 

Good job so far!
There are some issues that you still need to work on to prepare your project for the final evaluation but you are almost there!
# STATUS: REQUEST CHANGES :recycle: 
![soclose](https://user-images.githubusercontent.com/97100091/217936500-5a35b30d-aad8-4af5-aeff-199302ad83cc.gif)



## Suggested changes
_Check the comments under the review._

You can use as many of my suggestions as you want. If there is anything you would like to skip - feel free to do that. However, I strongly recommend you to take them into account as they can make your code better._
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2023-02-09 20:53 UTC, christianbiring1 commented on about.html
> +                </li>
- [ ] Kindly make sure when the user is on the about page, the link in the navigation bar is `home` to navigate on the home(`index`) page.
- [ ] Also, consider linking your link in the navigation bar with the corresponding section on the page. `i.e when the user clicks the link they are redirected to the exact section on the page(sponsors, program,...)`

2023-02-09 20:53 UTC, christianbiring1 commented on style.js
> +                </div>
[OPTIONAL]
- [ ] Kindly make sure on the mobile version, once the page is visited, the user can only see some of the `sponsors` and once the `SEE MORE` button is clicked, they can be able to see the remaining sponsor
`HINT: You may consider displaying half of the sponsor array elements at first and setting the other half hidden, and once the button is clicked all the elements are displayed on the UI. and the text content in the button change to SEE LESS`
![image](https://user-images.githubusercontent.com/97100091/217929104-30b3ed73-0bc2-49cf-84f8-e3f473ad61c4.png)

2023-02-09 20:53 UTC, christianbiring1 commented on style.css
> +.first-section {
- [ ] Kindly make sure the first section on the about section is well centered as in the original template

Your design :point_down: 
![Screenshot from 2023-02-09 22-26-32](https://user-images.githubusercontent.com/97100091/217930408-fb79b582-8b47-4fb2-9035-bd8570efa5f7.png)

2023-02-09 20:53 UTC, christianbiring1 commented on style.css
> +  .hamburger {
- [ ] Kindly make sure The CSS styling is built as **mobile-first**, media queries are used to change the design from mobile to desktop, not the other way around as it is the best practice and helps to reduce the code lines.
The media queries is supposed to be:
```css
@media screen and (min-width: 768px)
```

2023-02-09 20:53 UTC, christianbiring1 commented on style.css
> +  padding: 30px 0;
- [ ] Kindly make sure you stick to the design as much as possible. please consider adding this overlay on these images on the `about` page as is in the design.
`Hint: You may add the linear gradient to the background if the image was added background image`
Your design :point_down: 
![image](https://user-images.githubusercontent.com/97100091/217934773-c4b7e544-4f7a-4e08-9fee-1e41c9c25c9d.png)

Figma template :point_down: 
![image](https://user-images.githubusercontent.com/97100091/217935180-0bd573cb-fe05-4a94-83fe-b1745f828ca6.png)

2023-02-10 00:15 UTC, NahnahAJ approved these changes
## Project Status: APPROVED :green_circle: 
Hi @Gmanlove , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
<img src="https://media3.giphy.com/media/3oz9ZE2Oo9zRC/giphy.gif"/>

## Highlights
- [ ] Great pull request title and description :heavy_check_mark: :
- [ ] Professional README :heavy_check_mark: 
- [ ] All changes made:heavy_check_mark:

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-10 00:19 UTC, merged